import React from "react";

const Background: React.FC = () => {
  return (
    <div className="absolute inset-0 w-[1920px] h-[1440px] border border-gray-300 flex-col justify-start items-start inline-flex opacity-50 z-[-10]">
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
      <div className="justify-start items-start inline-flex">
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative bg-gray-100 border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
        <div className="w-24 h-24 relative border-r border-b border-gray-300" />
      </div>
    </div>
  );
};

export default Background;
